### ISSUE TITLE
path too long for Windows

### ISSUE THREAD

**Issue by AMPXIII** [boudinfl/pke#100]
Hi there,
First, congrats for the great job putting all this algorithms together, it is useful indeed.

Just one small detail: 
When using extractor.load_document(input="""Some literal string containing the text to analyse""")
If the text is really long, this method fails because it first tries to check if it is a path to a file before trying to treat as text.  This makes line 93 in base.py (if os.path.isfile(input):) fail.

I wondered if you have encountered this situation before and if you have a workaround for it.

Thanks a lot!

**Comment by ygorg** [comment]
Hello ! Thank you for the feedback and for reporting this error !

I currently don't have access to a windows.
This issue seem to be related to [this](https://docs.microsoft.com/fr-fr/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#maximum-path-length-limitation).
To fix this they propose to prepend `\\?\` to the path to make it an 'extended-length path'.

Could you please try to run the following code snippet and paste the results here ?

```python
import os
prefix = u'\\\\?\\'


path = os.listdir()[0]  # or any existing file
mod_path = os.path.join(u'\\\\?', path)

print(path)
print('This should be True: {}'.format(os.path.exists(path)))

print(mod_path)
print('This should be True: {}'.format(os.path.exists(mod_path)))
print()


path = """Short text that is less than 255 characters Short text that is less than 255 characters Short text that is less than 255 characters Short text that is less than 255 characters Short text that is less than 255 characters"""
mod_path = os.path.join(u'\\\\?', path)

print(path)
print('This should be False: {}'.format(os.path.exists(path)))

print(mod_path)
print('This should be False: {}'.format(os.path.exists(mod_path)))
print()


path = """Very long text that is more than 255 characters Very long text that is more than 255 characters Very long text that is more than 255 characters Very long text that is more than 255 characters Very long text that is more than 255 characters Very long text that is more than 255 characters."""
mod_path = os.path.join(u'\\\\?', path)

print(mod_path)
# This will maybe throw an exception
print('This should be False: {}'.format(os.path.exists(mod_path)))

print(path)
print('This should throw an exception')
print('This should be False: {}'.format(os.path.exists(path)))
```
