### ISSUE TITLE
Bug in single_tpr implementation

### ISSUE THREAD

**Issue by findoctor** [boudinfl/pke#109]
![image](https://user-images.githubusercontent.com/18277845/75022391-4e144400-5496-11ea-9153-14a07f7421dd.png)
I think you need to replace '0' here with the document index (let's say k) in the entire corpus. 
Because when you compute the topical importance W(w_i), it should be similarity between document_k ' s  topic distribution and w_i ' s topic distribution.

**Comment by ygorg** [comment]
Hi, thank for your interest.

I think that the `0` is linked to the fact that the input to `tf_vectorizer` is a list of one string (`[' '.join(doc)]`). Thus the result of `model.transform` is a list of one topic_distribution.

```python
tf = tf_vectorizer.fit_transform([' '.join(doc)])
distribution_topic_document = model.transform(tf)[0]
```
