### ISSUE TITLE
unable to find "en" model

### ISSUE THREAD

**Issue by elonMusk123007** [boudinfl/pke#110]
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
ubuntu 18.04 
python 3.6

**Comment by Oulaolay** [comment]
`python -m spacy download en
`
Try this code

**Comment by elonMusk123007** [comment]
@Oulaolay already did it output is as follows,

✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
Segmentation fault (core dumped)
