### ISSUE TITLE
Installation Issues.

### ISSUE THREAD

**Issue by koufounak** [boudinfl/pke#111]
Hello, i'm trying to install pke module to my system following the installation instructions at [](https://github.com/boudinfl/pke#installation). I'm using Python 3.7.4 and when i try the command `pip install git+https://github.com/boudinfl/pke.git` and i get:

 `Collecting git+https://github.com/boudinfl/pke.git
  Cloning https://github.com/boudinfl/pke.git to c:\users\koufo\appdata\local\temp\pip-req-build-resks_9l
Requirement already satisfied (use --upgrade to upgrade): pke==1.8.1 from git+https://github.com/boudinfl/pke.git in c:\users\koufo\anaconda3\lib\site-packages
Requirement already satisfied: nltk in c:\users\koufo\anaconda3\lib\site-packages (from pke==1.8.1) (3.4.5)
Requirement already satisfied: networkx in c:\users\koufo\anaconda3\lib\site-packages (from pke==1.8.1) (2.3)
Requirement already satisfied: numpy in c:\users\koufo\anaconda3\lib\site-packages (from pke==1.8.1) (1.16.5)
Requirement already satisfied: scipy in c:\users\koufo\anaconda3\lib\site-packages (from pke==1.8.1) (1.3.1)
Requirement already satisfied: spacy in c:\users\koufo\anaconda3\lib\site-packages (from pke==1.8.1) (2.2.3)
Requirement already satisfied: six in c:\users\koufo\anaconda3\lib\site-packages (from pke==1.8.1) (1.12.0)
Requirement already satisfied: sklearn in c:\users\koufo\anaconda3\lib\site-packages (from pke==1.8.1) (0.0)
Requirement already satisfied: unidecode in c:\users\koufo\anaconda3\lib\site-packages (from pke==1.8.1) (1.1.1)
Requirement already satisfied: future in c:\users\koufo\anaconda3\lib\site-packages (from pke==1.8.1) (0.18.2)
Requirement already satisfied: joblib in c:\users\koufo\anaconda3\lib\site-packages (from pke==1.8.1) (0.13.2)
Requirement already satisfied: decorator>=4.3.0 in c:\users\koufo\anaconda3\lib\site-packages (from networkx->pke==1.8.1) (4.4.0)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\koufo\anaconda3\lib\site-packages (from spacy->pke==1.8.1) (1.0.2)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in c:\users\koufo\anaconda3\lib\site-packages (from spacy->pke==1.8.1) (0.6.0)
Requirement already satisfied: blis<0.5.0,>=0.4.0 in c:\users\koufo\anaconda3\lib\site-packages (from spacy->pke==1.8.1) (0.4.1)
Requirement already satisfied: srsly<1.1.0,>=0.1.0 in c:\users\koufo\anaconda3\lib\site-packages (from spacy->pke==1.8.1) (1.0.1)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in c:\users\koufo\anaconda3\lib\site-packages (from spacy->pke==1.8.1) (1.1.3)
Requirement already satisfied: thinc<7.4.0,>=7.3.0 in c:\users\koufo\anaconda3\lib\site-packages (from spacy->pke==1.8.1) (7.3.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\koufo\anaconda3\lib\site-packages (from spacy->pke==1.8.1) (2.22.0)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\koufo\anaconda3\lib\site-packages (from spacy->pke==1.8.1) (3.0.2)
Requirement already satisfied: setuptools in c:\users\koufo\anaconda3\lib\site-packages (from spacy->pke==1.8.1) (41.4.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\koufo\anaconda3\lib\site-packages (from spacy->pke==1.8.1) (2.0.3)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in c:\users\koufo\anaconda3\lib\site-packages (from spacy->pke==1.8.1) (1.0.0)
Requirement already satisfied: scikit-learn in c:\users\koufo\anaconda3\lib\site-packages (from sklearn->pke==1.8.1) (0.21.3)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in c:\users\koufo\anaconda3\lib\site-packages (from thinc<7.4.0,>=7.3.0->spacy->pke==1.8.1) (4.36.1)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\koufo\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy->pke==1.8.1) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\koufo\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy->pke==1.8.1) (2019.9.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\koufo\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy->pke==1.8.1) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\koufo\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy->pke==1.8.1) (1.24.2)
Requirement already satisfied: importlib-metadata>=0.20; python_version < "3.8" in c:\users\koufo\anaconda3\lib\site-packages (from catalogue<1.1.0,>=0.0.7->spacy->pke==1.8.1) (0.23)
Requirement already satisfied: zipp>=0.5 in c:\users\koufo\anaconda3\lib\site-packages (from importlib-metadata>=0.20; python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy->pke==1.8.1) (0.6.0)
Requirement already satisfied: more-itertools in c:\users\koufo\anaconda3\lib\site-packages (from zipp>=0.5->importlib-metadata>=0.20; python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy->pke==1.8.1) (7.2.0)
Building wheels for collected packages: pke
  Building wheel for pke (setup.py): started
  Building wheel for pke (setup.py): finished with status 'done'
  Created wheel for pke: filename=pke-1.8.1-cp37-none-any.whl size=8755064 sha256=ac5f5f793e013da2cf978d9e77d922f4211dab2daac91d7a629e90973cd2f8c9
  Stored in directory: C:\Users\koufo\AppData\Local\Temp\pip-ephem-wheel-cache-98y9zysj\wheels\8d\24\54\6582e854e9e32dd6c632af6762b3a5d2f6b181c2992e165462
Successfully built pke
Note: you may need to restart the kernel to use updated packages.
  Running command git clone -q https://github.com/boudinfl/pke.git 'C:\Users\koufo\AppData\Local\Temp\pip-req-build-resks_9l'`

After this when i try `import pke` i get: 
`
  File "<ipython-input-11-6769976d5eff>", line 1, in <module>
    import pke

ModuleNotFoundError: No module named 'pke' `

**Comment by ygorg** [comment]
Hi, thanks for your interest !
Everything seem to look ok in the installation log.
You can check that `pke` was well installed using `pip list`, and that the `pip` used to perform the installation is the one python is using :
- `pip[3] -V`, `python[3] -m pip -V` : what python is pip using
- `where python[3]` : where is the python you are using (`where` seem to be a windows equivalent for bash `which`)

Also have you "restarted the kernel to use updated packages" ? Assuming you are in IPython or a jupyter notebook.

**Comment by koufounak** [comment]
Thanks for the responce. This was actually the problem, pip was installing modules to a different version of python. Now i installed pke to the correct version of python and while i can import pke, i'm running the script from the examples (bellow the installation chapter) and on this line i get `extractor.load_document(input='input.txt', language='en')` . This has something to do with spacy i think. (I have already executed the commands: 
`python -m nltk.downloader stopwords`
`python -m nltk.downloader universal_tagset`
`python -m spacy download en` .

Also these commands: `import spacy`
`spacy.load("en_core_web_sm")` run successfully.

**Comment by koufounak** [comment]
Ok i finally found the issue. I was executing the command `python -m spacy download en` as admin but i was doing that the project venv folder (`<project_name>/venvs/<my_venv>/Scripts`) instead of going to `Anaconda3/envs/<my_venv>/lib/site-packages`.
The latter worked.

**Comment by ygorg** [comment]
Cool ! If you have no further issue i'll close this issue.
