### ISSUE TITLE
NLTK ValueError: Transformation generated invalid chunkstring

### ISSUE THREAD

**Issue by alarictabaries** [boudinfl/pke#115]
I have an error when I try to extract keywords from the following abstract (in french), using TopicalPageRank model.

```python
extractor.load_document(input=abstract, language=lang) # lang is 'fr', abstract is the following abstrat
extractor.candidate_selection()
# <--- returns an error here
extractor.candidate_weighting()
```

> En supposant que l’impact anthropique des nuisances sonores occasionnées par les visiteurs d’un parc naturel pouvait être réduit par des actions de communication, nous avons élaboré un protocole interdisciplinaire associant bioacoustique et mesure d’efficacité des actions de communication, un protocole de mise en évidence de l’impact anthropique associé à un protocole de mesure d’efficacité des actions de communication. Une communication d’éco-sensibilisation simple sera comparée à une communication de sensibilisation engageante. Nous traitons les questions suivantes : est-ce que la sensibilisation des visiteurs les conduit à modifier leurs attitudes et comportements en vue de limiter leurs propres nuisances sonores ? Est-ce que l’engagement améliore la sensibilisation ? Nous détaillons ici les principaux concepts convoqués et la méthodologie suivie afin de discuter des premiers résultats.

```
ValueError: Transformation generated invalid chunkstring:
  <PRON><VERB><DET>{<NOUN>}<ADJ><SPACE><PUNCT><><PRON><SCONJ><DET>{<NOUN>}<DET>{<NOUN>}<DET><VERB><ADP><VERB><DET>{<NOUN>}<CCONJ><ADJ><ADP>{<NOUN>}<ADP><VERB><DET>{<ADJ><NOUN>}<ADJ><SPACE><PUNCT>
```

Full traceback : https://framabin.org/p/?a23dfbb23e778af5#8WOW5ogpiLHKNiB2s5ntKFILu6VTNRbP2iiINGeSynE=

**Comment by ygorg** [comment]
Hi, thanks for your report. I think I found the culprit. It seem that `est-ce` is tokenised and pos-tagged as `[('est', ''), ('-ce', 'PRON')]`, thus `est` have no pos which creates the empty tag in the chunkstring `...<PUNCT> <> <PRON>...`. This will happens with all the exceptions in [spacy/lang/fr/tokenizer_exceptions.py](https://github.com/explosion/spaCy/blob/f580302673ae16c673619603632378e5d390dacd/spacy/lang/fr/tokenizer_exceptions.py).

I am writing a spacy issue right now. I don't know what the correct way to fix this in `pke` would be. Maybe something like `pos = token.pos or token.tag`, but it might cause side effects.

**Comment by ygorg** [comment]
I files an issue here [spacy#5179](https://github.com/explosion/spaCy/issues/5179)

**Comment by ygorg** [comment]
I was provided a workaround code, i'll make a pull request tomorrow @alarictabaries.
