### ISSUE TITLE
Optimize pke.readers.RawTextReader

### ISSUE THREAD

**Issue by sp1thas** [boudinfl/pke#118]
Hi there,

When using `spacy` is a common practice to disable unnecessary components from the pipeline. However, `pke.readers.RawTextReader`, generates an `nlp` object using the default pipeline.

In my case, I'm trying to run topic rank algorithm in a large number of documents. The whole procedure could be optimized by excluding some `spacy` components (I.e: `parser`, `textcat`, `ner`).

`pke.readers.RawTextReader` does not pass any argument during `nlp` initiation (except `max_length`).

Would you be interested in adding this extra functionality?

If you agree, I'm available to contribute.

**Implementation example:**
```python
class RawTextReader(Reader):
    # [...]
    def read(self, text, **kwargs):
        disable = kwargs.get('disable')
        nlp = spacy.load(self.language, max_length=max_length, disable=disable)
```

**Comment by ygorg** [comment]
Hi ! Disabling some `spacy` components and keeping only the smallest subset of necessary components is indeed interesting. As `pke` only uses the  sentence tokenisation, and pos tagging.

I don't see why adding an argument for `disable` is necessary as the components used by `pke` are known and `spacy` is used only for loading the document.

In my opinion hard-coding the unnecessary component when loading the model is sufficient. The point would be to avoid adding parameters when possible.

A quick solution to this is the -- not very well documented -- [`spacy_model`]( https://github.com/BrunoBerisso/pke/blob/6f3afa81b6d90ecc231be8eebec9bb9917147f0c/pke/readers.py#L70) argument introduced in #105 for `load_document()`.

**Comment by sp1thas** [comment]
Hi @ygorg ,

I see your point, lets exclude these components in the hard-coding way.

I will make a double check and if everything works fine I will make a pull request.

Regarding the change you have made, I agree that the last line is not necessary. I think that excluding some components using `disable` parameter is enough in our case.

stay safe.
