### ISSUE TITLE
instaling ModuleNotFoundError: No module named 'sklearn'

### ISSUE THREAD

**Issue by funkbouya** [boudinfl/pke#120]
I having having issue with my Jupiter notebook saying module not found having installed scimitar learn already .I am pretty new to  programming but I have been stuck here for a while. Would appreciate if someone can help me out. 
Regards

**Comment by ygorg** [comment]
Hi, yes I saw something like this when searching for packages.
The [pypi/sklearn](https://pypi.org/project/sklearn/) page say:
`Use scikit-learn instead.`

So i think we must change the dependendy to `scikit-learn`.

Could you share the output of `pip list | grep learn` (you can launch this command in jupyter notebook directly) ?
