### ISSUE TITLE
Not gettings keyphrases as whole

### ISSUE THREAD

**Issue by Adnation** [boudinfl/pke#13]
When I try to extract keyphrases using TopicRank I get topics which are incomplete.

For example, for this text 

"In April, 2015, an earthquake of magnitude 7.8 on the Richter scale struck Nepal causing sheer havoc, destruction and death. The earthquake left over 8,000 people dead and injured more than 21,000. In the aftermath of the earthquake, the Government of India along with the Indian Armed Forces launched rescue and relief operations in Nepal and termed it as Operation Maitri. Nepali ex-servicemen of the Indian Armed Forces also joined in the operations for guidance in the difficult terrain. Indian Armed Forces were the first to reach Nepal with a helping hand. The helping hand included aircraft from the Indian Air Force and soldiers from the Indian Army for rescue mission on ground. Medical units were also pressed in for relief and engineering units were deployed to clear debris and roads. Besides transporting essential items to stranded citizens of Nepal, the army succeeded in rescuing thousands of people trapped in remote locations."

It  returned following keyphrases

indian arm forc -> 0.08056242226198376,
nepal -> 0.07927132788979997
relief oper -> 0.05869478479656734
earthquak -> 0.0531291849749921
rescu -> 0.04721509921710143

So the actual keyphrases should be 
Indian armed force
Nepal
Relief Operation
Earthquake and
Rescue

This is what my code is

`extractor = pke.TopicRank(input_file='data/data.txt')
extractor.read_document(format='raw')
extractor.candidate_selection()
extractor.candidate_weighting()
keyphrases = extractor.get_n_best(n=5)
print(keyphrases)`

So it there any problem in package or my interpretation is wrong?
If the output is corret then is there any way to get the output similar to the one I have shown?

**Comment by boudinfl** [comment]
Hi @Adnation,

The default output of `get_n_best()` is in stemmed form. To extract the surface forms of the keyphrases you should pass the `stemming=False` to that function.

To sum up, make sure you have the latest version of `pke` and replace `keyphrases = extractor.get_n_best(n=5)` with `keyphrases = extractor.get_n_best(n=5, stemming=False)`

Best,
