### ISSUE TITLE
"Transformation generated invalid " "chunkstring:\n  %s" % s

### ISSUE THREAD

**Issue by theCuriousHAT** [boudinfl/pke#132]
I am facing this issue "Transformation generated invalid " "chunkstring:\n  %s" % s
while running topic rank.
ValueError: Transformation generated invalid chunkstring:

However the data that I am passing to the model is a string.
Anybody else is facing the same issue?

**Comment by theCuriousHAT** [comment]
I was able to find the root cause for this,

I was using 1.2.0 en_core_web_sm
upgrading it to the latest version 2.2.5 resolved the issue.

**Comment by ygorg** [comment]
Hi,
Nice that you resolved your issue. Note that `python -m spacy validate` can provide helpful information.
Closing the issue.
