### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by janandreschweiger** [boudinfl/pke#133]
Hello! The pke-version of the yake extractor fails weightening the candidates for this text-file:
[data.txt](https://github.com/boudinfl/pke/files/4888940/data.txt)

**Error:**
`
.env/lib/python3.6/site-packages/pke/unsupervised/statistical/yake.py", line 368, in candidate_weighting
    term_right = tokens[j+1]
IndexError: list index out of range
`

**Code:**
extractor = pke.unsupervised.YAKE()
extractor.load_document(input='path/data.txt', language='en')
extractor.candidate_selection()
extractor.candidate_weighting()
keyphrases = extractor.get_n_best(n=10)

Unfortunately, we failed fixing this issue ourselves. The out-of-range error is raised for the token "allowed" / "allow" (line 30 of the text-file).
This is a critical issue, since we depend on your great package in two of our products.

Thank you!

**Comment by ygorg** [comment]
Hi, I also recently came accross this error, I'm fixing it now.

**Comment by janandreschweiger** [comment]
Thanks for your great support. :+1:

**Comment by ygorg** [comment]
Maybe it's not the same error I had, I'm wworking on it.

**Comment by janandreschweiger** [comment]
You're the best. This helped us a lot.
