### ISSUE TITLE
Pin requirements.txt package versions

### ISSUE THREAD

**Issue by mpangrazzi** [boudinfl/pke#135]
Hi!

What do you think about pinning `requirements.txt` package versions? 

This could avoid getting issues like [this one](https://github.com/explosion/spaCy/issues/5728) which are related to spacy `2.3.1` and for now have no fix other than downgrading spacy to `2.3.0`.

Maybe a `pip freeze > requirements.txt` could be enough.

**Comment by boudinfl** [comment]
This issue should be resolved in 4ec309c5152e661478e717b3143557744690bc41
