### ISSUE TITLE
Issue in trained model available for KEA

### ISSUE THREAD

**Issue by Shreya2k10** [boudinfl/pke#137]
Pre-trained model for kea (trained on  SemEval-2010 dataset.) as well as example model available at 'pke/examples/training_and_testing_a_kea_model/' were pickled using sklearn.externals.joblib (scikit-learn version ==0.20) but later sklearn.externals.joblib was removed. To fix deprication warning changes were commited on on Aug 20, 2019 in  pke/supervised/api.py which led to replacing 
from sklearn.externals import joblib 
with 
from joblib import load as load_model
Hence the two files that were pickled using sklearn.externals.joblib.dump were being unpickled using joblib.load. 
This led to following error-
ModuleNotFoundError: No module named 'sklearn.externals.joblib'
(Screenshot of complete error message is attached)
![Complete Error Message](https://user-images.githubusercontent.com/59021982/87557505-9d714000-c6d5-11ea-9fb0-7ef8640e9c44.png)

To resolve this issue make a virtual environment in python having scikit-learn==0.20. There unpickle the pre-trained model file and example model file for kea using sklearn.externals.joblib.job and pickle them using joblib.dump .
 
Note- This will still cause a warning UserWarning: Trying to unpickle estimator MultinomialNB from version 0.20.0 when using version 0.23.1. This might lead to breaking code or invalid results. Use at your own risk.UserWarning)
To resolve this estimator MultinomialNB from sklearn 0.23.1 needs to be used and model needs to be trained again using that.

**Comment by ygorg** [comment]
Thank you for reporting this ! I fixed it in #143.
