### ISSUE TITLE
Getting Value error when trying to give a some 50 small abstracts

### ISSUE THREAD

**Issue by swarnas89** [boudinfl/pke#139]
extractor.load_document(input=text, language='en')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-40-0c3dd778a55e> in <module>
----> 1 extractor.load_document(input=text, language='en')

~\Anaconda3\lib\site-packages\pke\base.py in load_document(self, input, **kwargs)
     91 
     92             # if input is an input file
---> 93             if os.path.isfile(input):
     94 
     95                 # an xml file is considered as a CoreNLP document

~\Anaconda3\lib\genericpath.py in isfile(path)
     28     """Test whether a path is a regular file"""
     29     try:
---> 30         st = os.stat(path)
     31     except OSError:
     32         return False

ValueError: stat: path too long for Windows

**Comment by ygorg** [comment]
Hello ! Thank you for the feedback and for reporting this error !
I think this might be the same thing as #100 

I currently don't have access to a windows.
This issue seem to be related to [this](https://docs.microsoft.com/fr-fr/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#maximum-path-length-limitation).
To fix this they propose to prepend `\\?\` to the path to make it an 'extended-length path'.

Could you please try to run the following code snippet and paste the results here ?

```python
import os
prefix = u'\\\\?\\'


path = os.listdir()[0]  # or any existing file
mod_path = os.path.join(u'\\\\?', path)

print(path)
print('This should be True: {}'.format(os.path.exists(path)))

print(mod_path)
print('This should be True: {}'.format(os.path.exists(mod_path)))
print()


path = """Short text that is less than 255 characters Short text that is less than 255 characters Short text that is less than 255 characters Short text that is less than 255 characters Short text that is less than 255 characters"""
mod_path = os.path.join(u'\\\\?', path)

print(path)
print('This should be False: {}'.format(os.path.exists(path)))

print(mod_path)
print('This should be False: {}'.format(os.path.exists(mod_path)))
print()


path = """Very long text that is more than 255 characters Very long text that is more than 255 characters Very long text that is more than 255 characters Very long text that is more than 255 characters Very long text that is more than 255 characters Very long text that is more than 255 characters."""
mod_path = os.path.join(u'\\\\?', path)

print(mod_path)
# This will maybe throw an exception
print('This should be False: {}'.format(os.path.exists(mod_path)))

print(path)
print('This should throw an exception')
print('This should be False: {}'.format(os.path.exists(path)))
```

**Comment by ygorg** [comment]
In #143 I changed the way we check whether an input is raw text or a file path. It should work now.
