### ISSUE TITLE
KeyError: 'nepali'

### ISSUE THREAD

**Issue by upasana-mittal** [boudinfl/pke#151]
`File "/code/src/....py", line 12, in <module>
    import pke
  File "/usr/local/lib/python3.6/site-packages/pke/__init__.py", line 5, in <module>
    from pke.base import LoadFile
  File "/usr/local/lib/python3.6/site-packages/pke/base.py", line 31, in <module>
    lang_stopwords = {get_alpha_2(l): l for l in stopwords._fileids}
  File "/usr/local/lib/python3.6/site-packages/pke/base.py", line 31, in <dictcomp>
    lang_stopwords = {get_alpha_2(l): l for l in stopwords._fileids}
  File "/usr/local/lib/python3.6/site-packages/pke/base.py", line 29, in <lambda>
    get_alpha_2 = lambda l: LANGUAGE_CODE_BY_NAME[l]
KeyError: 'nepali'`

**Comment by ygorg** [comment]
Hi,
this error has theoretically been fixed 5 hours ago, please try downloading `pke` again.
If the error still occur please let me know !

**Comment by upasana-mittal** [comment]
I have tried 3 times in past two hours and still facing it. Kindly look into it.

**Comment by ygorg** [comment]
Oh ok, sorry the inconvenience, I tried 10 minutes ago and it worked.
So, could you share the whole error ? (using [pastebin](https://pastebin.com) for example)

**Comment by upasana-mittal** [comment]
Its working now. I tried again. Thanks.

**Comment by ygorg** [comment]
Great ! Sorry the inconvenience !
