### ISSUE TITLE
the line 442 in the get_n_best function in yake.py is not same as base.py

### ISSUE THREAD

**Issue by ChengjinLi** [boudinfl/pke#152]
in base.py
「# sort candidates by descending weight
        best = sorted(self.weights, key=self.weights.get, reverse=True)」
but in yake.py 
it's 「 # sort candidates by ascending weight
        best = sorted(self.weights, key=self.weights.get, reverse=False)」

**Comment by ygorg** [comment]
Hello,
Thé fact that the `get_n_best` function is not the same in Yake is counter intuitive I agree.
But this is normal, because in Yake 0 is the best score and +♾ is the worse score.
