### ISSUE TITLE
WARNING:root:No spacy model for 'fr' language. 

### ISSUE THREAD

**Issue by ilucas75** [boudinfl/pke#153]
Hi,

using the non-english language example I get the following warning:

**WARNING:root:Falling back to using english model. There might be tokenization and postagging errors. A list of available spacy model is available at https://spacy.io/models.**

not clear to me if the code for french text is reliable or not?

**Comment by ygorg** [comment]
If this error message is displayed, the results won't be as good as they should.
Please verify that the french spacy model is downloaded using `python -m spacy validate`.
And download it if it isn't already using `python -m spacy download fr`.

Please let me know if this fixes your issue !

**Comment by ilucas75** [comment]
yes thank you! it because before your comment I use to download !python -m spacy download fr_core_news_md

instead of fr_core_news_sm
