### ISSUE TITLE
Windows: Marisa-trie setup error 

### ISSUE THREAD

**Issue by Paralosva** [boudinfl/pke#155]
Hi, I've got this problem

  Building wheel for marisa-trie (setup.py) ... error
  ERROR: Command errored out with exit status 1:
  command: 'C:\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = (...)
  cwd: C:\Users\usuario\AppData\Local\Temp\pip-install-j1km3x_o\marisa-trie_e0da6083b720408ebc3909bf87c1fa82\
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_clib
  building 'libmarisa-trie' library
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": 
https://visualstudio.microsoft.com/visual-cpp-build-tools/

  ERROR: Failed building wheel for marisa-trie
  Running setup.py clean for marisa-trie
Failed to build marisa-trie

I've installed Microsoft's C++ 14.0 but still not working

Any help?
Thanks!

**Comment by ygorg** [comment]
Hi,
Yes marisa-trie is not maintained anymore and can be troublesome to install.
Theoretically the dependency was removed in #149, please try reinstalling PKE with the latest version, there should be no problem.
Please let me know if you encounter any problem with marisa-trie in the newer version.
Have a nice day !
