### ISSUE TITLE
 ERROR: HTTP error 404 while getting https://github.com/ygorg/pke/archive/fixes.zip

### ISSUE THREAD

**Issue by cuczy** [boudinfl/pke#156]
sorry I can't find that, where can I use this zip? Thank you very much

**Comment by ygorg** [comment]
Hi, I don't remember the original issue where I mentionned this link.
But the changes I made in "https://github.com/ygorg/pke/archive/fixes.zip" were incorporated in the master branch of pke in #143.
So there really nothing interesting anymore about "https://github.com/ygorg/pke/archive/fixes.zip".
