### ISSUE TITLE
Hitting "array is too big" error when loading a 3.72MB text file with 9K lines

### ISSUE THREAD

**Issue by vikramkone** [boudinfl/pke#16]
Using the pke script as-is shown in the githud readme page ie, using topic rank

C:\Python27\lib\site-packages\unidecode\__init__.py:50: RuntimeWarning: Surrogate character u'\ud83d' will be ignored. You might be using a narrow Python build.
  return _unidecode(string)
C:\Python27\lib\site-packages\unidecode\__init__.py:50: RuntimeWarning: Surrogate character u'\ude0a' will be ignored. You might be using a narrow Python build.
  return _unidecode(string)
C:\Python27\lib\site-packages\unidecode\__init__.py:50: RuntimeWarning: Surrogate character u'\ude1d' will be ignored. You might be using a narrow Python build.
  return _unidecode(string)
Traceback (most recent call last):
  File "E:\Projects\NLP\KeyPhraseExtraction.py", line 17, in <module>
    extractor.candidate_weighting()
  File "C:\Python27\lib\site-packages\pke\unsupervised.py", line 437, in candidate_weighting
    self.topic_clustering(threshold=threshold, method=method)
  File "C:\Python27\lib\site-packages\pke\unsupervised.py", line 384, in topic_clustering
    candidates, X = self.vectorize_candidates()
  File "C:\Python27\lib\site-packages\pke\unsupervised.py", line 365, in vectorize_candidates
    X = np.zeros((len(C), len(dim)))
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

**Comment by yannick-c** [comment]
Just taking a quick guess here, but did you build your own python 2.7? Or did you pay attention that you downloaded the correct one. The first few warnings look like your python was built with the wrong unicode flags.

I know you're using windows, but on linux you would have to explicitly enable unicode support upon running configure with the `--enable-unicode=ucs4` flag I think. Don't know how you do that on windows.

**Comment by boudinfl** [comment]
I confirm what @yannick-c says about unicode.

The ValueError can also be due to the version of Python that you have installed (32bits or 63bits). Here is a similar problem and solution on stackoverflow : [https://stackoverflow.com/questions/42727181/valueerror-array-is-too-big-when-loading-googlenews-vectors-negative](https://stackoverflow.com/questions/42727181/valueerror-array-is-too-big-when-loading-googlenews-vectors-negative)
