### ISSUE TITLE
pke can't find spacy models

### ISSUE THREAD

**Issue by Vitalijus0** [boudinfl/pke#162]
![image](https://user-images.githubusercontent.com/47828695/118410516-776f5000-b698-11eb-90eb-01e031c522c5.png)

**Comment by ygorg** [comment]
Hi,
This should is a bug. Could you share your `spacy` version (`pip list | grep "spacy"`) please ?

In the mean time you can preload spacy model as such:
```python
import pke
import spacy

nlp =spacy.load('en_core_web_sm')

e = pke.unsupervised.MultipartiteRank()
e.load_document(text, language='en', spacy_model=nlp)
```

**Comment by Vitalijus0** [comment]
Hi, 
Thank you for the quick response, it seems there was some issues with the preloaded language model, with your help I was able to solve it. Thanks
