### ISSUE TITLE
You can't install it

### ISSUE THREAD

**Issue by Monish-k** [boudinfl/pke#167]
![Screenshot 2021-06-11 at 9 42 39 PM](https://user-images.githubusercontent.com/60218655/121716699-f6bc3c00-cafd-11eb-8121-432127df1cd0.png)

**Comment by ygorg** [comment]
Hi, I don't understand what causes your error, do you have more information ?
Have you tried looking at the logs, like the error message tells you ?

What version of `pip` are you using ? (`pip3 --version`)

[A StackOverflow response](https://stackoverflow.com/a/64362429/14476967) says to re-install a package, maybe you can try that:
`apt-get install -y --reinstall ca-certificates`

**Comment by Monish-k** [comment]
pip3 version is 20.2.4
Tried with apt-get , it worked on my linux kernel , but it still won't install on my Mac !.
Also , is this a open source project? am I allowed to fork and contribute?

**Comment by ygorg** [comment]
I don't know what the error you encounter comes from, sorry I cannot be of more help, though it seem like a pip or local environment problem.
Alternatively you can clone the repo and then install it via pip:
```bash
git clone https://github.com/boudinfl/pke
pip install pke/
rm -rf pke/
```

Yes, this is an open source project, you can fork and contribute !
Although our policy for adding new models to the master branch isn't quite clear, you are more than welcome to create your own fork.
