### ISSUE TITLE
Foreign Language Support (e.g. Chinese, Japanese)

### ISSUE THREAD

**Issue by BrandonKMLee** [boudinfl/pke#171]
Currently https://github.com/boudinfl/pke/blob/master/pke/readers.py#L177 

Model used
`!python -m spacy download zh`
https://github.com/explosion/spaCy/tree/master/spacy/lang/zh
https://spacy.io/models/zh

```import pke
extractor = pke.unsupervised.TopicRank()
extractor.load_document(input=result, language='zh')
extractor.candidate_selection()
extractor.candidate_weighting()
keyphrases = extractor.get_n_best(n=10)
```

The text is generated through
```from trafilatura import fetch_url, extract
url = 'https://std.stheadline.com/daily/article/2394542/%E6%97%A5%E5%A0%B1-%E6%B8%AF%E8%81%9E-%E6%96%B0%E8%81%9E%E8%BF%BD%E6%93%8A-%E7%99%BD%E7%9F%B3%E5%8D%81%E5%85%AC%E9%A0%83%E5%9C%B0%E6%93%AC%E9%99%90%E5%BA%B7%E6%A8%82%E7%94%A8%E9%80%94'
downloaded = fetch_url(url)
result = extract(downloaded, target_language='zh')
```

**Comment by ygorg** [comment]
Hi, I don't understand what problem you encounter ?
Does pke not use the spacy chinese model ?

Alternatively, have you tried passing `spacy_model` to the `load_document` function ?
```python
nlp = spacy.load('zh')
extractor.load_document(input=result, language='zh', spacy_model=nlp)
```

**Comment by BrandonKMLee** [comment]
@ygorg this flag was not used `spacy_model=nlp`, will test in a moment.
