### ISSUE TITLE
Scaling yake with pke

### ISSUE THREAD

**Issue by subhamkhemka** [boudinfl/pke#174]
Hi

Thanks for creating this library.

I am using the yake extractor for my use case. I have over 200K sentences which need to be run as a batch workload.

Could you provide suggestions on how I could speed up the execution ?

**Comment by ygorg** [comment]
Hi, until now pke is a development library and is not intended to be efficient in terms of time of execution.
Please feel free to change the code to use threads and optimize it as you wish.
