### ISSUE TITLE
Benchmarking scripts

### ISSUE THREAD

**Issue by luffycodes** [boudinfl/pke#179]
Hey, I was wondering where to find the benchmarking scripts for semeval dataset ? Any help with be greatly appreciated !

**Comment by luffycodes** [comment]
Found it on another repository

**Comment by luffycodes** [comment]
Hello,

The repo https://github.com/boudinfl/ake-datasets has the datasets.

Are there any benchmarking scripts though?

Thank you,

**Comment by boudinfl** [comment]
Hi @luffycodes,

We have another repo https://github.com/boudinfl/ake-benchmarking that should contain the becnhmarking scripts that you need :)

f.

**Comment by luffycodes** [comment]
hello @boudinfl is there repo public? the above link gives a 404 error !

**Comment by boudinfl** [comment]
Sorry about that, please have a look at this Colab about benchmarking models with pke [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/keyphrasification/hands-on-with-pke/blob/main/part-3-benchmarking-models.ipynb)
