### ISSUE TITLE
does it support east asian language like Chinese, Japanese...

### ISSUE THREAD

**Issue by loveJasmine** [boudinfl/pke#18]

**Comment by boudinfl** [comment]
Dear @loveJasmine ,

I have not tried using pke with asian languages but I see no reason why it should not work if you pre-process the input files. Stemming and the stopwords list are the only language dependent components that we use from nltk.

Please refer to https://github.com/boudinfl/pke#non-english-languages for more info on how to use pke for non english languages.

I would be pleased to try, if you provide me with a bunch of documents.

f.

**Comment by loveJasmine** [comment]
there is ‘boundary’ symbol(ex:blank) in English-like language, but in Asian language , all character are successive with each other in one sentence.
