### ISSUE TITLE
Reasoning for removing KP-Miner

### ISSUE THREAD

**Issue by dennlinger** [boudinfl/pke#185]
Hi, I just discovered that the latest release removed some implementations (among those, KP-Miner), without much reasoning.

Can you maybe share some light on why some methods were removed?
In particular, according to [this study](https://arxiv.org/pdf/1905.05044.pdf), it seems that KP-Miner is still relatively competitive to some of the other approaches.

Any answer is appreciated!

**Comment by boudinfl** [comment]
Hi @dennlinger,

Sorry about that, I just removed some models during refactoring for v.2.0.0. 

My view is that, for statistical models, there is few differences between KP-Miner and YAKE and I believed that the latter was more effective. I was not aware of the experimental results you mention, I could somewhat easily re-include KP-Miner if you think it is relevant, please let me know.

f.

**Comment by dennlinger** [comment]
Hi @boudinfl,
thanks for your response!
While the study is relatively clear in the results quality of KP-Miner, I was trying to find whether there are any other papers reporting similar findings. As the overall values strike me quite low (for all methods), it would be great to have some more insights to back it up.

Given that it is still available through the older version, I will experiment with that version on my current data and report back if I can provide some insights of my own. I'll let you know about my findings here :)

Thanks again for taking the feedback seriously and getting back so quickly!
Best,
Dennis

**Comment by boudinfl** [comment]
I'll let this issue open until you can give some results on your data.

f.

**Comment by boudinfl** [comment]
To let you know that I added back KP-miner on 6729b8feaada2f067d87b90e189ca0135ff6e61b

f.

**Comment by dennlinger** [comment]
In the meantime, I've run the two methods on the test set of KP20k; the macro scores give reason to believe that the predictions are significantly different.

Thanks again for adding it back in!
