### ISSUE TITLE
All zero weights when use a newly trained Kea Model

### ISSUE THREAD

**Issue by xiangli13** [boudinfl/pke#19]
Hi boudinfl,

when I try to train a new kea model using given lvl-2 data set and train.reader.stem.final reference data, the model just don't seem to work. It always output keywords with all zero weights like below.

[(u'angl densiti', 0.0),
 (u'significantli improv local', 0.0),
 (u'tell that node', 0.0),
 (u'boundari indic', 0.0),
 (u'smaller statist mean', 0.0),
 (u'clearli that iter', 0.0),
 (u'undesir high deploy', 0.0),
 (u'dbe vs non\u2212db', 0.0),
 (u'range-bas and range-fre', 0.0),
 (u'60 70 basic', 0.0)]

here is the code:
import pke

input_dir = r'lvl-2/'
# load the DF counts from file
df_counts = pke.load_document_frequency_file(input_file='out.gz',delimiter='\t')

# train a new Kea model
pke.train_supervised_model(input_dir=input_dir,
                           reference_file='ref/train.reader.stem.final',
                           model_file='output_mdl.pickle',
                           df=df_counts,
                           format='corenlp',
                           use_lemmas=False,
                           stemmer='porter',
                           model=pke.supervised.Kea(),
                           language ='english',
                           extension='xml')

Thank you!

Best,
Xiang

**Comment by boudinfl** [comment]
I am not sure what is going on with your training procedure, did you re-compute the idf weights (the out.gz) and are you sure that the training files are correctly named (i.e. as in the reference file).

There is a script located at examples/train-model.py that can be used to training a new Kea model, please consider trying it.

Best,

f.
