### ISSUE TITLE
Is there a way to manage hyphenated compound words as a whole

### ISSUE THREAD

**Issue by fbottazzoli** [boudinfl/pke#195]
Hello,
I'm using PositionRank to extract keyphrases from a set of sentences often containing hyphenated compound workds (eg. state-of-the-art, business-as-usual, end-of-life). I would like them to be managed as whole but they are considered as separate words (I think this is due to the fact that - character is part of string.punctuation and then removed).
Is there a way to consider them as a single word?
Thank you 
Francesca

**Comment by fbottazzoli** [comment]
Hello @boudinfl, yes, it works!
Thank you
Francesca

**Comment by boudinfl** [comment]
Great,

I am closing this issue then.

f.
