### ISSUE TITLE
Library dependency issues with the last commit

### ISSUE THREAD

**Issue by hammadmukhtar21** [boudinfl/pke#199]
Hi, I used your repository's this variant "https://github.com/boudinfl/pke.git@dc4d5f21e0ffe64c4df93c46146d29d1c522476b" in my code which is currently not available after the last commit. I face library issues in the whole code due to the updated repository. So, kindly share this repository.

**Comment by ygorg** [comment]
Hi, thanks for using pke. I cannot access to the link you provide (not found error).
What error are you facing and what line of code triggered it ?
