### ISSUE TITLE
Langcode "ge" does not work with spacy

### ISSUE THREAD

**Issue by cbartz** [boudinfl/pke#201]
German langcode ``ge`` https://github.com/boudinfl/pke/blob/master/pke/lang.py#L22 is not recognized by spacy, which leads to a missing ``stopwords`` assignment in https://github.com/boudinfl/pke/blob/master/pke/lang.py#L34-L40 .

Observed with pke  2.0.0 and spacy 3.3.1.

**Comment by shyambhu-mukherjee** [comment]
german langcode is `de` btw

**Comment by shyambhu-mukherjee** [comment]
isn't that supposed to be `de`?

**Comment by cbartz** [comment]
Yes.
