### ISSUE TITLE
Keyword dataset

### ISSUE THREAD

**Issue by aradhana298** [boudinfl/pke#204]
Can anyone suggest a dataset on which unsupervised keyword detection algorithms like multipartite  graph, BERT etc can be applied to check the accuracy , precision etc.

**Comment by ygorg** [comment]
Please check [(Campos et .al, 2020)](https://www.sciencedirect.com/science/article/pii/S0020025519308588#sec0018) for a comprehensive list of keyword extraction datasets. You can also search for keyword/keyphrase extraction/generation papers for a more recent overview.
