### ISSUE TITLE
sklearn is deprecated, breaks PKE 

### ISSUE THREAD

**Issue by gregorybrooks** [boudinfl/pke#209]
Apparently you are supposed to replace sklearn with scikit-learn in your requirements files and your import statements. They have disabled sklearn in PyPi and so now when I build PKE it won't execute, says there is no sklearn module installed. 

See https://pypi.org/project/sklearn/

I can give more details if you haven't already encountered this problem.

**Comment by ygorg** [comment]
Thanks for reporting this, it should be fixed with #208
