### ISSUE TITLE
error while installing pke

### ISSUE THREAD

**Issue by albalatejazer** [boudinfl/pke#210]
i used this command to install pke. "pipenv install git+https://github.com/boudinfl/pke.git#egg=pke"

i got this message error.
PS D:\code\Minerse\Seekerse\seekerse-backend> pipenv install git+https://github.com/boudinfl/pke.git#egg=pke
Loading .env environment variables...
Installing git+https://github.com/boudinfl/pke.git#egg=pke...
Error:  An error occurred while installing git+https://github.com/boudinfl/pke.git#egg=pke!
Error text: Collecting pke
  Cloning https://github.com/boudinfl/pke.git to c:\users\mr. albalate\appdata\local\temp\pip-install-kew1wbx9\pke_f55f0af1a65341da872a1b10bcd18258
  Resolved https://github.com/boudinfl/pke.git to commit 5af1f817e0211c33ac3f90e1e86bb5c1283448e8
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: nltk in c:\users\mr. albalate\.virtualenvs\seekerse-backend-7evesh8q\lib\site-packages (from pke->-r c:\users\mrffcb~1.alb\appdata\local\temp\pipenv-4m3wo6s2-requirements\pipenv-6vo8yxwn-requirement.txt (line 1)) (3.7)   
Collecting networkx
  Using cached networkx-2.8.8-py3-none-any.whl (2.0 MB)
Requirement already satisfied: numpy in c:\users\mr. albalate\.virtualenvs\seekerse-backend-7evesh8q\lib\site-packages (from pke->-r c:\users\mrffcb~1.alb\appdata\local\temp\pipenv-4m3wo6s2-requirements\pipenv-6vo8yxwn-requirement.txt (line 1)) (1.23.5)
Requirement already satisfied: scipy in c:\users\mr. albalate\.virtualenvs\seekerse-backend-7evesh8q\lib\site-packages (from pke->-r c:\users\mrffcb~1.alb\appdata\local\temp\pipenv-4m3wo6s2-requirements\pipenv-6vo8yxwn-requirement.txt (line 1)) (1.9.3)Collecting sklearn
  Using cached sklearn-0.0.post1.tar.gz (3.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  Running command git clone --filter=blob:none --quiet https://github.com/boudinfl/pke.git 'C:\Users\Mr. Albalate\AppData\Local\Temp\pip-install-kew1wbx9\pke_f55f0af1a65341da872a1b10bcd18258'
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package

      If the previous advice does not cover your use case, feel free to report it at
      https://github.com/scikit-learn/sklearn-pypi-package/issues/new
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

This is likely caused by a bug in pke. Report this to its maintainers.
Installation Failed

**Comment by ygorg** [comment]
Thanks for reporting this, it should be fixed with #208
