### ISSUE TITLE
How can I read multiple documents as a corpus? 

### ISSUE THREAD

**Issue by tomleung1996** [boudinfl/pke#22]
Hi,
I am using `pke.unsupervised.TfIdf` to extract key phrases, but it seems that the function only takes one file as input. I have a csv file contains multiple documents and I want to read them together as a corpus, can I use pke to achieve this?  Can I use string as input?

**Comment by tomleung1996** [comment]
Thanks for your reply, I decided to split the csv file

**Comment by boudinfl** [comment]
No problem.
