### ISSUE TITLE
Issue importing pke

### ISSUE THREAD

**Issue by jundl77** [boudinfl/pke#5]
After installing pke with

```pip install git+https://github.com/boudinfl/pke.git``` 

it seems like pke is not imported correctly. More specifically, pke resolves to it's containing file and not to the package, thus nothing is found, at least for me. 

I am on ubuntu with python2.7 and I looked into the directory where pke is installed (```/usr/local/lib/python2.7/dist-packages/pke```) and that content is the same as the ```pke``` folder in this repository. To be honest, I don't really understand the error. It seems like it is expecting/finding a ```pke.py``` file, but I don't see any?

**Comment by jundl77** [comment]
Nevermind, my mistake, sorry.

**Comment by boudinfl** [comment]
OK
