### ISSUE TITLE
Feature request: pos_blacklist

### ISSUE THREAD

**Issue by TristanH** [boudinfl/pke#51]
Hiya -- first off, this library is amazing. Thank you so much for creating it 🙏

It would be immensely useful to be able to add a parameter to the `candidate_filtering` function called something like `pos_blacklist`.

The idea would be that one could filter out e.g "all adverbs" or all patterns "NNS VBZ".

I'm having to do this manually in a loop right now after candidate selection, which is suboptimal for a variety of reasons. Hopefully this request isn't too usecase-specific, or I'm not just missing an easy way to do this -- feel free to close if I am.

**Comment by boudinfl** [comment]
It's done, please update your install (`pip install -U git+https://github.com/boudinfl/pke.git`) and have a look at the documentation [here](https://boudinfl.github.io/pke/build/html/base.html#pke.base.LoadFile.candidate_filtering).

**Comment by TristanH** [comment]
Amazing! 👏 Thank you so much :)
