### ISSUE TITLE
feed directly text as input

### ISSUE THREAD

**Issue by miguelwon** [boudinfl/pke#53]
Hi,
Is it possible to feed directly text as input instead of from a text file? I want to give it as input pos tagged sentences.

**Comment by miguelwon** [comment]
Sorry, didn't see the example in the readme.

**Comment by boudinfl** [comment]
No problem @miguelwon 
Let me know if you have any issues with `pke`
Best,

**Comment by miguelwon** [comment]
Ok, thanks.  I don't want to give it raw text as input but preprocessed text. I know I could create a bunch of files with the preprocessed text but it would be easier if `read_text` could receive as input already preprocessed text. Just tried to feed it directly with something like

`extractor.sentences = [ {"words": [w1,w2,...], "POS":[tag1,tag2,...]},...]
`

but didn't work.
