### ISSUE TITLE
How to load a document which is too long and some bytes are non-utf8？

### ISSUE THREAD

**Issue by lusuon** [boudinfl/pke#66]
I am trying to use pke to extract keywords from papers with some non-utf8 bytes .

When I use the function **load_document()**, I got a problem:

1. If use the path as input, it will cause an exception that some bytes can't be decode.
But seems I can't do anything to avoid /ignore the error.
 
2. When I tried to use string(the content of the txt) as input directly, the program threw an exception "the the path is too long for windows", I guess the function os.stat(path)  can‘t accept such a long string.

In this situation, how can I load such a long and partly non-utf8 file?

**Comment by boudinfl** [comment]
Hi @lusuon,

There is an `encoding` argument that you can pass to the `load_document()` method in order to read non utf-8 files. Please have a look at the code documentation of this method [here](https://boudinfl.github.io/pke/build/html/base.html#pke.base.LoadFile.load_document).

f.
