### ISSUE TITLE
 E050

### ISSUE THREAD

**Issue by Mahadev001** [boudinfl/pke#71]
Tried to load a text file  using 

extractor = pke.unsupervised.KPMiner()

# 2. load the content of the document.
extractor.load_document(input = 'C:\Users\mahadev\Downloads\401KPlan.txt',  language = 'en')

and getting following error: 
[E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

What am i doing wrong?

**Comment by boudinfl** [comment]
I think you do not have the spacy english model installed on your machine.

Please try to install the model using``python -m spacy download en`` or have a look at the [spacy website](https://spacy.io/usage/models).

f.

**Comment by Jcerwin** [comment]
I ran into the same issue with this latest version. I was able to solve the issue by manually reloading ‘en'

`python -m spacy download en`
