### ISSUE TITLE
Keyphrase extraction not from text file

### ISSUE THREAD

**Issue by Mahadev001** [boudinfl/pke#72]
From most of your examples I have noticed that a text file path is being provided as an input. Is there any capability to actually take input of string from any  other data type such as a list or a dictionary?

For example: say my input corpus has been stored in a list and  I would like to provide the list as an input for the keyphrase extraction. Is it possible?

**Comment by boudinfl** [comment]
You can provide a string as input, please have a look at the documentation [here](https://boudinfl.github.io/pke/build/html/tutorials/input.html).

**Comment by Mahadev001** [comment]
Yes, Thanks. I figured it out.  Amazing toolkit. Would be helpful if there is more documentation suggesting which model to useful in which kind of applications.
