### ISSUE TITLE
Unicode decode error while using KPMiner

### ISSUE THREAD

**Issue by dipaweshpawarsn** [boudinfl/pke#76]
While using KPMiner I am getting Unicode decode error. This is essentially during reading of Document frequency file which is hardcoded to pke\models\df-semeval2010.tsv.gz

Please find the detailed error below.

UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-13-0552bbff75b0> in <module>()
     21 # minimum similarity for clustering, and the method parameter defines the
     22 # linkage method
---> 23 extractor.candidate_weighting()
     24 
     25 # print the n-highest (10) scored candidates

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pke\unsupervised\statistical\kpminer.py in candidate_weighting(self, df, sigma, alpha)
    119             logging.warning('LoadFile._df_counts is hard coded to {}'.format(
    120                 self._df_counts))
--> 121             df = load_document_frequency_file(self._df_counts, delimiter='\t')
    122 
    123         # initialize the number of documents as --NB_DOC-- + 1 (current)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pke\utils.py in load_document_frequency_file(input_file, delimiter)
     55 
     56         # populate the dictionary
---> 57         for row in df_reader:
     58             frequencies[row[0]] = int(row[1])
     59 

~\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 104: character maps to <undefined>

**Comment by boudinfl** [comment]
Hi @dipaweshpawarsn,

Do you also get that error when using the TfIdf model?

f.

**Comment by dipaweshpawarsn** [comment]
I will have to check that as I tried it 3 months ago

**Comment by dipaweshpawarsn** [comment]
> Hi @dipaweshpawarsn,
> 
> Do you also get that error when using the TfIdf model?
> 
> f.

No I have not tried it.

**Comment by boudinfl** [comment]
I am not able to reproduce your issue on my computer. Can you try to update your `pke` install and re-try?

Thanks,

**Comment by palle-k** [comment]
I am able to reproduce this issue in an Ubuntu-18.04 Docker container.

**Comment by palle-k** [comment]
The fix is to run the following:

```bash
apt-get install locales
locale-gen en_US.UTF-8
update-locale LC_ALL= en_US.UTF-8 LANG= en_US.UTF-8
export PYTHONIOENCODING=utf8
```

Not sure whether all lines are necessary.

**Comment by MisooKim** [comment]
I fixed the same bug as follows.

File: pke/util.py
Function: load_document_frequency_file(input_file, delimiter='\t'):
Lines: 51 ~ 53
Fixed code: (adding encoding="utf8" when open the file)
```
    # open the input file
    with gzip.open(input_file, 'rt', encoding="utf8") if input_file.endswith('.gz') else \
            codecs.open(input_file, 'rt', encoding="utf8") as f:
        # read the csv file
        df_reader = csv.reader(f, delimiter=delimiter)
```
