### ISSUE TITLE
extractor.load_document(input='/path/to/input.txt', language='en')

### ISSUE THREAD

**Issue by kjung2** [boudinfl/pke#78]
Hi, I'm so sorry to ask this simple question, but I've been struggling with this for days and think I should ask you this. I would really appreciate if you make some suggestions.

I believe I installed pke correctly (I can import pke).

I believe I installed spacy correctly (I could import spacy and do the following: nlp = spacy.load('en_core_web_sm')

And I tried the first two lines of your minimal example, which is:

extractor = pke.unsupervised.TopicRank()
extractor.load_document(input='C-1.txt', language='en')

I downloaded your C-1. txt and I also tried my sample .txt files and get the following error messages:

Traceback (most recent call last):
  File "C:\Users\kjung2\AppData\Local\Programs\Python\Python37-32\test_pke.py", line 7, in <module>
    extractor.load_document(input='C-1.txt', language='en')
  File "C:\Users\kjung2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pke\base.py", line 107, in load_document
    doc = parser.read(text=text, path=input, **kwargs)
  File "C:\Users\kjung2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pke\readers.py", line 74, in read
    max_length=max_length)
  File "C:\Users\kjung2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\spacy\__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "C:\Users\kjung2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\spacy\util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

I do have the .txt files in the following path:
C:\Users\kjung2\AppData\Local\Programs\Python\Python37-32
where I have the test_pke.py which currently has only the two lines in the above.

I know that this must be a really silly question for you, but I really want to use your codes. Please help and thanks again.

**Comment by kjung2** [comment]
I fixed my problem with my friends' help.

**Comment by Saumya-Rai** [comment]
@kjung2 I am facing the same problem. Could you please tell me how you solved the issue?

**Comment by boudinfl** [comment]
Hi @kjung2 and @Saumya-Rai,

Sorry for the late response.

The issue seems to come from spacy. Can you try to (re)-dowload the english model using the following instruction: `python -m spacy download en` ?

**Comment by Saumya-Rai** [comment]
Thanks a lot! Works fine for me now

**Comment by fighting41love** [comment]
`python -m spacy download en ` failed to solve the problem.
The link `https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#egg=en_core_web_sm==2.0.0` doesn't exist any more.
