### ISSUE TITLE
ValueError: The number of observations cannot be determined on an empty distance matrix.

### ISSUE THREAD

**Issue by dhariyalbhaskar** [boudinfl/pke#79]
I m facing this particular error while running the below code.

```
import pke
import string
from nltk.corpus import stopwords

# 1. create a MultipartiteRank extractor.


pos = {'NOUN', 'PROPN', 'ADJ'}
stoplist = list(string.punctuation)
stoplist += ['-lrb-', '-rrb-', '-lcb-', '-rcb-', '-lsb-', '-rsb-']
stoplist += stopwords.words('english')
stoplist += stop

# 2. load the content of the document.
for i, item in enumerate(df["Complaints"]):
    extractor = pke.unsupervised.MultipartiteRank()
    
    extractor.load_document(item)

# 3. select the longest sequences of nouns and adjectives, that do
#    not contain punctuation marks or stopwords as candidates.

    try:
        extractor.candidate_selection(pos=pos, stoplist=stoplist)
        extractor.candidate_weighting(alpha=1.1, threshold=0.74, method='average')
        keyphrases = extractor.get_n_best(n=10)
        print(keyphrases)
    except ZeroDivisionError:
        print()

```

**Error**
```

ValueError                                Traceback (most recent call last)
<ipython-input-24-03b5c5c29248> in <module>
     23     try:
     24         extractor.candidate_selection(pos=pos, stoplist=stoplist)
---> 25         extractor.candidate_weighting(alpha=1.1, threshold=0.74, method='average')
     26         keyphrases = extractor.get_n_best(n=10)
     27         print(keyphrases)

~/.local/lib/python3.5/site-packages/pke/unsupervised/graph_based/multipartiterank.py in candidate_weighting(self, threshold, method, alpha)
    213 
    214         # cluster the candidates
--> 215         self.topic_clustering(threshold=threshold, method=method)
    216 
    217         # build the topic graph

~/.local/lib/python3.5/site-packages/pke/unsupervised/graph_based/multipartiterank.py in topic_clustering(self, threshold, method)
    102 
    103         # compute the clusters
--> 104         Z = linkage(Y, method=method)
    105 
    106         # form flat clusters

~/.local/lib/python3.5/site-packages/scipy/cluster/hierarchy.py in linkage(y, method, metric, optimal_ordering)
   1110                          "finite values.")
   1111 
-> 1112     n = int(distance.num_obs_y(y))
   1113     method_code = _LINKAGE_METHODS[method]
   1114 

~/.local/lib/python3.5/site-packages/scipy/spatial/distance.py in num_obs_y(Y)
   2382     k = Y.shape[0]
   2383     if k == 0:
-> 2384         raise ValueError("The number of observations cannot be determined on "
   2385                          "an empty distance matrix.")
   2386     d = int(np.ceil(np.sqrt(k * 2)))

ValueError: The number of observations cannot be determined on an empty distance matrix.
```

Please let me know if somebody has resolved the mentioned issue.

**Comment by corei5** [comment]
Hello @dhariyalbhaskar 

I think you try to get input a Dataframe called Complaints. As far as I know, you need to give text or XML file as like as "SemEval 2010" dataset. 


Code: 

import pke

# initialize keyphrase extraction model, here MultipartiteRank
extractor = pke.unsupervised.MultipartiteRank()

# load the content of the document, here document is expected to be in raw
# format (i.e. a simple text file) and preprocessing is carried out using spacy
extractor.load_document(input='/path/to/input.txt', language='en')

# keyphrase candidate selection, in the case of TopicRank: sequences of nouns
# and adjectives (i.e. `(Noun|Adj)*`)
extractor.candidate_selection()

# candidate weighting, in the case of TopicRank: using a random walk algorithm
extractor.candidate_weighting()

# N-best selection, keyphrases contains the 10 highest scored candidates as
# (keyphrase, score) tuples
keyphrases = extractor.get_n_best(n=10)
print(keyphrases )

OR:

import pke
import string
from nltk.corpus import stopwords

# 1. create a MultipartiteRank extractor.
extractor = pke.unsupervised.MultipartiteRank()

# 2. load the content of the document.
extractor.load_document(input='path/to/input.xml')

# 3. select the longest sequences of nouns and adjectives, that do
#    not contain punctuation marks or stopwords as candidates.
pos = {'NOUN', 'PROPN', 'ADJ'}
stoplist = list(string.punctuation)
stoplist += ['-lrb-', '-rrb-', '-lcb-', '-rcb-', '-lsb-', '-rsb-']
stoplist += stopwords.words('english')
extractor.candidate_selection(pos=pos, stoplist=stoplist)

# 4. build the Multipartite graph and rank candidates using random walk,
#    alpha controls the weight adjustment mechanism, see TopicRank for
#    threshold/method parameters.
extractor.candidate_weighting(alpha=1.1,
                              threshold=0.74,
                              method='average')

# 5. get the 10-highest scored candidates as keyphrases
keyphrases = extractor.get_n_best(n=10)

print(keyphrases )


[1] https://github.com/boudinfl/pke/blob/master/pke/unsupervised/graph_based/multipartiterank.py
