### ISSUE TITLE
python version to use pke

### ISSUE THREAD

**Issue by fatimalaoui** [boudinfl/pke#81]
Hi,
I'm trying to implement a supervised algorithm using pke 
I would like to know if it works with the python 3.7 version? i'm not able to install it using: **pip3 install pke** (  Could not find a version that satisfies the requirement pke (from versions: )
No matching distribution found for pke)
and even this command:**"pip install git+https://github.com/boudinfl/pke.git"** does not work.
Thank you in advance

**Comment by syedsadiqalinaqvi** [comment]
I've faced a similar issue while installing. A workaround is to simply clone/download the pke repository and copy it in your project.

**Comment by ericzon** [comment]
pip install git+https://github.com/boudinfl/pke.git
or
pipenv install git+https://github.com/boudinfl/pke.git#egg=pke
should do the trick.
