### ISSUE TITLE
question about the algorithm

### ISSUE THREAD

**Issue by ailoz2** [boudinfl/pke#87]
Hi everyone,
I’m new in this forum and new to the world of AI and machine learning. I am very interested in supervised learning. 
And I actually want to learn more about those algorithms.
After some researches, I understood that KEA is based on supervised learning but I’m not sure if i understood it as it should :
As inputs we give the model : the document from where we want to extract keywords, and a model of training and also the number of key words we would like to have?
So this model is served to compare and find out whether in our document there are words that already were keywords and exists on our model? If so , they are automatically considered as keyword? And for the rest , the kea apply the TF IDF and calculate the “distance” and apply also the naïve bayes model to have a list of word ranked according to the probability?
Is Wingnus based on the same algorithm or is it different?
I hope I was clear.. I don’t know if what I understood is the right thing or not? I will be pleased if someone can tell me and correct this information if incorrect.

**Comment by boudinfl** [comment]
Hi @ailoz2,

Thanks for using `pke`. I encourage you to look at [this blog post](http://bdewilde.github.io/blog/2014/09/23/intro-to-automatic-keyphrase-extraction/) as well as this [survey paper](http://acl2014.org/acl2014/P14-1/pdf/P14-1119.pdf) about keyphrase extraction.

f.
