### ISSUE TITLE
stat: path too long for Windows

### ISSUE THREAD

**Issue by stefashkaa** [boudinfl/pke#89]
Hello!
I've received an Exception associated with a too long path for Windows during to `extractor.load_document(input=content, language='en', normalization='lemmatization')`:
`Exception: stat: path too long for Windows`

For input, I used the content text from the article (https://en.wikipedia.org/wiki/London). It seems that python method `if os.path.isfile(input)` from `load_document()` throws this exception. Could you add the bool flag  `is_file` as the parameter to avoid that when long content is sent as an input?

**Comment by boudinfl** [comment]
Hi @stefashkaa,

This appears to be an issue from the python `os` module [see here](https://bugs.python.org/issue33105). The easiest way to fix this would be to write the content text to a file and load it.

f.
