### ISSUE TITLE
YAKE implementation error!

### ISSUE THREAD

**Issue by vitordouzi** [boudinfl/pke#90]
YAKE has some implementation errors. For example, (1) the stopwords list MUST be more complete, so we use this [one here](https://github.com/LIAAD/yake/tree/master/yake/StopwordsList); (2) the way we compute the stopwords and not stopwords weight is different; (3) how to calculate the frequency of co-occurrence needs to consider punctuation. And some others...

In addition, I have already made the necessary changes to the proper functioning of YAKE in PKE, but as I have no privileges to do pull request, I leave in my [git the corrected version](https://github.com/LIAAD/yake/tree/master/pke).

All of these errors have been detrimental to YAKE's performance, see the table below for quick experimentation, where the first result is the [original YAKEs version ](https://github.com/LIAAD/yake)and the results of pke_yake_vX.Y represent X = 0 is the default version implemented by PKE and X = 1 is my corrections. Y = 1 is using the stopwords lists of nltk (using by PKE) and Y = 2 using [these stopwords lists](https://github.com/LIAAD/yake/tree/master/yake/StopwordsList).
 ```
                                           app        map
0  110-PT-BN-KP_Yake_n3_w1_seqm-0.90_f-NonC.out  0.415100 
1                110-PT-BN-KP_pke_yake_v0.1.out  0.154000 
2                110-PT-BN-KP_pke_yake_v0.2.out  0.394600 
3                110-PT-BN-KP_pke_yake_v1.1.out  0.351800 
4                110-PT-BN-KP_pke_yake_v1.2.out  0.417600 
                                                 app        map
0  500N-KPCrowd-v1.1.1_Yake_n3_w1_seqm-0.90_f-NonC.out  0.138800 
1                500N-KPCrowd-v1.1.1_pke_yake_v0.1.out  0.079300 
2                500N-KPCrowd-v1.1.1_pke_yake_v0.2.out  0.137200 
3                500N-KPCrowd-v1.1.1_pke_yake_v1.1.out  0.129900 
4                500N-KPCrowd-v1.1.1_pke_yake_v1.2.out  0.151300 
                                      app        map
0  PubMed_Yake_n3_w1_seqm-0.90_f-NonC.out  0.044500 
1                PubMed_pke_yake_v0.1.out  0.018800 
2                PubMed_pke_yake_v0.2.out  0.001000 
3                PubMed_pke_yake_v1.1.out  0.037400 
4                PubMed_pke_yake_v1.2.out  0.040400 
                                      app        map
0  Inspec_Yake_n3_w1_seqm-0.90_f-NonC.out  0.215800 
1                Inspec_pke_yake_v0.1.out  0.078400 
2                Inspec_pke_yake_v0.2.out  0.145400 
3                Inspec_pke_yake_v1.1.out  0.162500 
4                Inspec_pke_yake_v1.2.out  0.177900 
                                           app        map
0  SemEval2010_Yake_n3_w1_seqm-0.90_f-NonC.out  0.124700 
1                SemEval2010_pke_yake_v0.1.out  0.066500 
2                SemEval2010_pke_yake_v0.2.out  0.095900 
3                SemEval2010_pke_yake_v1.1.out  0.109800 
4                SemEval2010_pke_yake_v1.2.out  0.112500 
                                   app        map
0  WKC_Yake_n3_w1_seqm-0.90_f-NonC.out  0.312400 
1                WKC_pke_yake_v0.1.out  0.201300 
2                WKC_pke_yake_v0.2.out  0.322800 
3                WKC_pke_yake_v1.1.out  0.318400 
4                WKC_pke_yake_v1.2.out  0.348800
```

Alternatively, I suggest using the version of [YAKE that is in pypi](https://pypi.org/project/yake/). It is updated frequently.

**Comment by boudinfl** [comment]
Hi @vitordouzi,

Sorry for the **very** late response, I finally have time to spend on checking YAKE implementation.

About (1), every model in pke uses the same *default* stopword list (the one provided by nltk) which can be changed using the `stoplist` parameter in `candidate_selection()`. My position here is that I do not want to have separate/different stopword lists for each model as this, as you know, greatly impacts performance.

About (2) and (3), I mainly relied on the model description in the ECIR 2018 paper to make this re-implementation and I may have missed some points. I will change my code according to the [one you provided](https://github.com/LIAAD/yake/tree/master/yake/StopwordsList).

**Comment by boudinfl** [comment]
So, these are the differences I found between ours and your implementations:

1) In `candidate_selection()`, you added a filter to remove candidates that contain a first/last word with less than 3 characters.

2) In `context_building()`, you changed how contexts are computed from the whole sentence to blocks. Blocks are sequences of `in vocabulary` words.

3) In `_feature_extraction()`, you changed how WRel is computed by removing the addition of PL and RL. **This is different from the equation 4 in the ECIR 2018 paper**.

4) In `candidate_weighting()`, you change how word weights are computed for stopwords. Here words that are less than 3 characters are also considered as stopwords.
