### ISSUE TITLE
Is there a way to specify number of extracted key phrase from each sentence? 

### ISSUE THREAD

**Issue by Hannabrahman** [boudinfl/pke#92]
Is there a way to specify number of extracted key phrase from each sentence? 
For example specifying to extract only one (highest score) key phrase from each sentence of a given input text?

Please advise
Thanks

**Comment by boudinfl** [comment]
There is currently no straighforward way to do that in `pke`but it could be achieved by first extracting the N-best keyphrases from the document and then loop through them to only keep one keyphrase per sentence.
