### ISSUE TITLE
any supporting model for Chinese?

### ISSUE THREAD

**Issue by marcusau** [boudinfl/pke#96]
As topic mentioned

Thanks

**Comment by boudinfl** [comment]
Hi @marcusau,

This is not currently planned but unsupervised models should work 'fine' if you provide preprocessed Chinese text.

f.

**Comment by boudinfl** [comment]
I just had a quick look at `spacy` (which `pke` uses fo preprocessing) and it seems that it does not support Chinese yet.

**Comment by marcusau** [comment]
Actually, I can train my own Chinese Word2Vec or FastText model on myself.

Would you provide some guideline how to incorporate my own model into the pke open library?

**Comment by boudinfl** [comment]
There are currently no model in `pke` that require word representations.

The first approach would be to test an unsupervised model (let's say TextRank) on a Chinese document and see what is going on. Two things should be done for that: redefining `load_document()` to handle chinese text and `candidate_selection()` to identify Chinese Noun phrases as keyphrase candidates.

**Comment by boudinfl** [comment]
This issue is closed due to no new activities, feel free to re-open in case of new comments.
