### ISSUE TITLE
Running extractor.candidate_weighting with empty parameters gives error

### ISSUE THREAD

**Issue by ccjspijk** [boudinfl/pke#99]
When running `extractor.candidate_weighting()` this happens:

WARNING:root:LoadFile._df_counts is hard coded to C:\Users\chris\PycharmProjects\onderzoek\venv\lib\site-packages\pke\models\df-semeval2010.tsv.gz
Traceback (most recent call last):
  File "C:/Users/chris/.PyCharmCE2019.2/config/scratches/test.py", line 19, in <module>
    extractor.candidate_weighting()
  File "C:\Users\chris\PycharmProjects\onderzoek\venv\lib\site-packages\pke\unsupervised\statistical\tfidf.py", line 80, in candidate_weighting
    df = load_document_frequency_file(self._df_counts, delimiter='\t')
  File "C:\Users\chris\PycharmProjects\onderzoek\venv\lib\site-packages\pke\utils.py", line 58, in load_document_frequency_file
    for row in df_reader:
  File "C:\Users\chris\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 104: character maps to <undefined>

**Comment by boudinfl** [comment]
The error looks like an encoding error during loading DF counts. Can you try opening/reading the file `C:\Users\chris\PycharmProjects\onderzoek\venv\lib\site-packages\pke\models\df-semeval2010.tsv.gz` ?

**Comment by ccjspijk** [comment]
I can open the file manually with notepad++ and see the content, however if I try to load the path into the program like this: 

`df = pke.load_document_frequency_file(input_file='C:\\Users\\chris\\PycharmProjects\\onderzoek\\venv\\lib\\site-packages\\pke\\models\\df-semeval2010.tsv.gz')

extractor.candidate_weighting(df=df)`

then I get the encoding error.

According to notepad++ the file is encoded as UTF-8

**Comment by boudinfl** [comment]
hum, I don't know what going on here. Can you try to resinstall `pke` and use Python 3.7+?

**Comment by ccjspijk** [comment]
I tried installing Python 3.7.1 with pke because I couldn't get pke to install with 3.7.4. This did not fix the problem. I changed the function load_document_frequency_file() in utils.py

from `with gzip.open(input_file, 'rt') if input_file.endswith('.gz') else \
            codecs.open(input_file, 'rt') as f:`

to `with gzip.open(input_file, 'rt', encoding='utf8') if input_file.endswith('.gz') else \
            codecs.open(input_file, 'rt', encoding='utf8') as f:`

I got the code running with this change in the source code, I still have not figured out what the underlying issue is but I can continue my project for now. Thanks!

**Comment by boudinfl** [comment]
That means that the default encoding in your config is not utf-8. Do you use a windows-based machine?

**Comment by ccjspijk** [comment]
Yes, I use Windows 10 so it will probably pick Windows-1252 when reading a file, apparently Windows doesn't allow you to change the default encoding. I changed my workspace and file settings to UTF-8 in PyCharm but that didn't fix the problem for some reason. For now I will use my previous post as temporary solution, I might have to look into a more permanent solution later.
